#! /bin/sh
#directory /home/$USER/.config/bspwm/bspwmrc

sxhkd &

#set status variables for potentially connected displays
VGA=$(cat /sys/class/drm/card0-VGA-1/status) 
HDMI=$(cat /sys/class/drm/card0-HDMI-A-1/status)

#assign desktops to primaty and VGA display
if [ $VGA == "connected" ]; then
  bspc monitor VGA-1 -s eDP-1
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8
  bspc monitor VGA-1 -d 9 10
fi

#assign desktops to primary and HDMI display
if [ $HDMI == "connected" ]; then 
  bspc monitor eDP-1  -d 1 2 3 4 5 6 7 8
  bspc monitor HDMI-1 -d 9 10
fi

#assign all desktops to primary screen when no other displays are connected
if [ $HDMI == "disconnected" ] && [ $VGA == "disconnected" ]; then
  bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config click_to_focus  true

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#running external rule script at startup
$HOME/dotfiles/externalRules.sh

#bspc config external_rules_command home/niels/.config/bspwm/external-rules.sh
