#!/bin/bash
ELECTRON_ENABLE_HIDPI_SCALING=1 \
exec ~/.local/opt/outlook/outlook \
  --enable-features=UseOzonePlatform \
  --ozone-platform=wayland \
  --user-data-dir=/home/niels/.config/outlook-nativefier-profile \
  --disk-cache-dir=/home/niels/.cache/outlook-nativefier-cache \
  "$@"

