alias ll='ls -alF --color=auto'
alias docked="dockd --set docked"
alias undocked="dockd --set undocked"
alias ssh="TERM=xterm-256color ssh"
alias vpnSplit="sudo openvpn --config /home/niels/vpnconfigs/splitTunnel.ovpn --daemon"
alias vpnKillSplit='sudo pkill -f "/home/niels/vpnconfigs/splitTunnel.ovpn"'
