alias ssh="TERM=xterm-256color ssh"

alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias docked="dockd --set docked"
alias undocked="dockd --set undocked"
alias vpnSplit="sudo openvpn --config /home/niels/vpnconfigs/splitTunnel.ovpn --daemon"
alias vpnKillSplit='sudo pkill -f "/home/niels/vpnconfigs/splitTunnel.ovpn"'

