#
# ~/.bash_profile
#

[[ -f ~/.profile ]] && . ~/.profile

if [[ -z $WAYLAND_DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    exec start-hyprland
fi

# if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
#     exec startx
# fi

# [[ -f ~/.bashrc ]] && . ~/.bashrc

