#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

#start on desktop 2 (tied to 1-key)
bspc desktop --focus ^2

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
