#
# ~/.bash_profile
#

[[ -f ~/.profile ]] && . ~/.profile

if [[ -z $WAYLAND_DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    exec Hyprland
fi

#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
#    exec startx
#fi

# [[ -f ~/.bashrc ]] && . ~/.bashrc

# Created by `pipx` on 2025-06-06 09:06:02

