#!/bin/sh

#set background
source "$HOME/dotfiles/work/env-vars"

#set qt display settings
export QT_SCALE_FACTOR=1.5
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_STYLE_OVERRIDE=kvantum

# Source scripts from xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
fi

#set wallpaper
feh --bg-fill $wallpaper

#lock screen on startup
$HOME/dotfiles/work/lock.sh --text "welcome"

#disable screen timeout
xset s off -dpms &

#change cursor appearance
xsetroot -cursor_name left_ptr &

#start compositor
picom -b

# monitor setup
autorandr -c

#start key map for window manager
sxhkd &

#start window manager
bspwm -c $HOME/.config/bspwm/bspwmrc

