#!/bin/sh

#set qt display settings
export QT_SCALE_FACTOR=1.5
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_STYLE_OVERRIDE=kvantum

# Source scripts from xinitrc.d
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
fi

# monitor setup
autorandr --change

#disable screen timeout
xset s off -dpms &

#change cursor appearance
xsetroot -cursor_name left_ptr &

#start compositor
picom -b

#lock screen on startup
$HOME/dotfiles/work/lock.sh --text "welcome"

#start key map for window manager
sxhkd &

#start window manager
bspwm -c $HOME/.config/bspwm/bspwmrc

